apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/var/lib/kubernetes/kube-scheduler.kubeconfig"
leaderElection:
  leaderElect: true
  resourceLock: "leases"
  namespace: "kube-system"
  name: "kube-scheduler"
  leaseDuration: 15s
  renewDeadline: 10s
  retryPeriod: 2s